# Generated by Django 5.0 on 2023-12-24 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_token_device'),
        ('shop', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='shop.shop', verbose_name='Shop'),
        ),
    ]
