# Generated by Django 5.0 on 2023-12-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_moneyhistory_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneyhistory',
            options={'verbose_name': 'Money History', 'verbose_name_plural': 'Money Histories'},
        ),
        migrations.AlterField(
            model_name='moneyhistory',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
